/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/budget` | `/budget`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/discover` | `/discover`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/itinerary` | `/itinerary`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/translate` | `/translate`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/budget` | `/budget`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/discover` | `/discover`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/itinerary` | `/itinerary`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/translate` | `/translate`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/budget${`?${string}` | `#${string}` | ''}` | `/budget${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/discover${`?${string}` | `#${string}` | ''}` | `/discover${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/itinerary${`?${string}` | `#${string}` | ''}` | `/itinerary${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/translate${`?${string}` | `#${string}` | ''}` | `/translate${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/budget` | `/budget`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/discover` | `/discover`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/itinerary` | `/itinerary`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/translate` | `/translate`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
